### ISSUE TITLE
Could you please help update the README file? I plan to use my own data for training the scene renderer. Thank you very much for your assistance!

### ISSUE THREAD

**Issue by RaymondLam857** [zju3dv/NeuSC#3]
Could you please help update the README file? I plan to use my own data for training the scene renderer. Thank you very much for your help!

**Comment by EricRohmer89** [comment]
Could you please help update the README file? I plan to use my own data for training the scene renderer. Thank you very much for your help!

**Comment by haotongl** [comment]
I have added custom data tutorial.
