### ISSUE TITLE
data processing scripts

### ISSUE THREAD

**Issue by RaymondLam857** [zju3dv/NeuSC#4]
I'm interested in obtaining the data processing scripts mentioned in the paper. Could you please provide information on where I can find or access these scripts?
Thank you very much

**Comment by haotongl** [comment]
Hi, thank you for your attention! Do you need multiple servers to run one scene colmap scripts in parallel at the same time? May I know approximately how many images your dataset contains? If there are less than 20,000 images, there should be no need to use it. Times square has 300,000 images, so I used this algorithm.

**Comment by RaymondLam857** [comment]
Thanks for your answer, my dataset does not have 20000 images. 
I am a beginner in the NeRF. I am interested in building my own scene for this project. After reading the method of processing image datasets in the paper, I don't know how to specifically process my own image data sets.
Because I will only use colmap to build static three-dimensional objects, I don't know how to use Colmap to handle such changing scenes and there are other files in the demo besides image files, and I don't know how they are generated.
Finally thank you very much again！

**Comment by haotongl** [comment]
20,000 images doesn't sound like multiple servers are needed to calibrate the data in parallel. I will release related calibration scripts. BTW, do your images have prepared timestamps (this is a prerequisite for running neural scene chronology.)

**Comment by haotongl** [comment]
20,000 images doesn't sound like multiple servers are needed to calibrate the data in parallel. I will release related calibration and processing scripts. BTW, do your images have prepared timestamps (this is a prerequisite for running neural scene chronology.)

**Comment by RaymondLam857** [comment]
"timestamps" seems to me to be the prefix of the image file name, right? I don't know if I understand correctly, thank you for your answer.

**Comment by haotongl** [comment]
Yes, you’ve understood it correctly.

**Comment by haotongl** [comment]
I have updated the README.

**Comment by RaymondLam857** [comment]
Thank you for your contribution and help
