### ISSUE TITLE
How to run colmap sfm on a collection of images with different timestamps

### ISSUE THREAD

**Issue by RaymondLam857** [zju3dv/NeuSC#5]
In my understanding, sparse reconstruction models vary for images captured at different timestamps. I'm not understand about the process of running COLMAP to execute Structure-from-Motion (SfM) on an image dataset. Should all images with different timestamps be placed in a single folder？

**Comment by haotongl** [comment]
Hi, thanks for your attention! The scene of different timestamps share the same sparse reconstruction model. Therefore, you only need to place all images with different timestamps  in a single folder and then run colmap!
