### ISSUE TITLE
May I ask which version of MMSegmentation in scripts/semantic/prepare_data.py is used? I encountered an error during operation.

### ISSUE THREAD

**Issue by RaymondLam857** [zju3dv/NeuSC#6]
ImportError: cannot import name 'inference_segmentor' from 'mmseg.apis' . How to solve it.

**Comment by haotongl** [comment]
Hi，thanks for your attention! You should firstly install mmseg package.
I recently discovered that for a new environment, I will encounter various problems when installing mmseg, and solving them is very trivial and time-consuming. So I would recommend directly using my previously installed environment, I exported my environment configuration using conda env export > environment.yaml, you can use conda env create -f environment.yml to load the environment directly.

**Comment by haotongl** [comment]
[environment.txt](https://github.com/zju3dv/NeuSC/files/14431103/environment.txt)
